crud_app/urls.py
from django.urls import path
from crud_app import views

app_name = 'crud_app'

urlpatterns = [
    path('',views.ContaListView.as_view(),name='list'),
    path('create/',views.ContaCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.ContaUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.ContaDeleteView.as_view(),name='delete'),
    path('detail/<int:pk>/',views.ContaDetailView.as_view(),name='detail'),
]

crudfornecedor/urls.py
from django.contrib import admin
from django.urls import path, include
from crud_app import views
from user import views

urlpatterns = [
    path('admin/',admin.site.urls,name='admin'),
    path('crud_app/',include('crud_app.urls',namespace='crud_app')),
    path('', include('user.urls')),
]

user/urls.py
from django.urls import path
from crud_app import views
from django.contrib.auth.views import LogoutView
from user.models import *

from user.views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("register/", RegisterView.as_view(), name="register"),
    path("films/", Filmlist.as_view(), name='film-list'),
]

htmx_urlpatterns = [
    path('check_username/', check_username, name='check-username'),
    path('add-film/', add_film, name='add-film')
]

urlpatterns += htmx_urlpatterns

crud_app/models.py
from enum import unique
from tabnanny import verbose
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Conta(models.Model):
    id = models.BigAutoField(primary_key=True)
    desc = models.CharField(max_length=200,verbose_name='Descrição')
    fornecedor = models.ForeignKey('Fornecedor', on_delete=models.CASCADE)

    class Meta:
        managed = False
        db_table = 'crud_app_conta'
        verbose_name_plural = 'Conta'

    def __str__(self):
        return "{} - {}".format(self.fornecedor, self.desc)
 
    def get_absolute_url(self):
        return reverse('index')

class Fornecedor(models.Model):
    id = models.BigAutoField(primary_key=True)
    nome = models.CharField(max_length=256)
    documento = models.CharField(unique=True, max_length=256)

    class Meta:
        managed = False
        verbose_name_plural = 'Fornecedor'
        db_table = 'crud_app_fornecedor'

    def __str__(self):
        return "{}".format(self.nome)

    def get_absolute_url(self):
        return reverse('index')

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass


class Film(models.Model):
    name= models.CharField(max_length=255, unique=True )
    users = models.ManyToManyField(User, related_name='films') # user.films.all()

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

crud_app/views.py
from urllib import request
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (TemplateView,ListView,CreateView,DeleteView,UpdateView,DetailView)
from . import models


class ContaListView(ListView):
    template_name = 'crud_app/tabela.html'
    model = models.Conta

#    def get_queryset(self):
#        user = self.request.user
#        return user.fornecedor.all()
#
class ContaCreateView(CreateView):
    template_name = 'crud_app/tabela.html'
    fields = ("desc","fornecedor")
    model = models.Conta
    success_url = reverse_lazy("crud_app:list")

class ContaDeleteView(DeleteView):
     model = models.Conta
     template_name= 'crud_app/excluir-cadastro.html'
     success_url = reverse_lazy("crud_app:list")

class ContaUpdateView(UpdateView):
    template_name = 'crud_app/cadastro.html'
    fields = ("desc","fornecedor")
    model = models.Conta
    success_url = reverse_lazy("crud_app:list")

class ContaDetailView(DetailView):
    model = models.Conta 
    template_name = 'crud_app/detail.html'


def create_list(request):
    name = request.POST.get('')

user/views.py
from django.shortcuts import render
from django.http.response import HttpResponse, HttpResponsePermanentRedirect
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import *
from django.contrib.auth import get_user_model

from user.forms import RegisterForm
from user.models import Film
# Create your views here.

class IndexView(TemplateView):
     template_name = 'index.html'
class Login(LoginView):
    template_name = 'registration/login.html'

class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        form.save()  # save the user
        return super().form_valid(form)

def check_username(request):
    username = request.POST.get('username')
    if get_user_model().objects.filter(username=username).exists():
        return HttpResponse("This username already exists")
    else:
        return HttpResponse("")


class Filmlist(ListView):
    template_name = 'registration/films.html'
    model = Film
    context_object_name = 'films'


    def get_queryset(self):
        user = self.request.user
        return  user.films.all()

def add_film(request):
    name = request.POST.get('filmname')
    
    # add film
    film = Film.objects.create(name=name)
    
    # add the film to the user's list
    request.user.films.add(film)

    # return template fragment with all the user's films
    films = request.user.films.all()
    return render(request, 'registration/film-list.html', {'films': films})

crud_app/templates/crud_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Safegold - Conta Fornecedor</title>{% endblock %}
    <link rel="shortcut icon" href="https://safegold.com.br/wp-content/themes/safeGold/assets/img/favicon.png">
    <link rel="shortcut icon" href="{% static 'images/safegold.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"><link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://unpkg.com/htmx.org@1.8.2"></script>
    {% block styles %}{% endblock %}
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark sg-dark justify-content-between" style="background-color:#414442">
            <div class="navbar-collapse">
                <a class="navbar-brand d-flex" href="{% url 'index' %}">
                    <img src="{% static "img/Safegold.svg" %}" height="30" alt="Safegold" class="mx-4" id="safegold">
                </a>
                {% if user.is_authenticated %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white font-weight-bold" href="{% url 'film-list' %}">Cadastrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white font-weight-bold" href="{% url 'crud_app:list' %}">Tabela</a>
                    </li>
                </ul> 
            </div>
            <div>
                <form class="form-inline d-flex justify-content-right">
                    <button class="btn btn-warning my-2 my-sm-0 mx-4" type="submit">
                        <a class="nav-link text-dark font-weight-bold" href="{% url 'admin:index' %}">Admin</a>
                    </button>
                    <button class="btn btn-warning my-2 my-sm-0 mx-4" type="submit">
                        <a class="nav-link text-dark font-weight-bold" href="{% url 'logout' %}">Sair</a>
                    </button>
                </form>
                {% else %}
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white font-weight-bold" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white font-weight-bold" href="{% url 'register' %}">Cadastre-se</a>
                    </li>
                </ul>

                {% endif %}
            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
        <script src="{% static 'js/jquery-3.6.1.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>	   
    {% block scripts %}
    {% endblock scripts %}
</body>

</html>

crud_app/templates/crud_app/cadastro.html
{% extends 'crud_app/base.html' %} 
{% load static %} 
{% load crispy_forms_tags%} 
{% block title %}
<title>Cadastro</title>
{% endblock title %} 
{% block content %}
<h1 class="d-flex justify-content-center mt-3">
  Cadastro de Contas e Fornecedores
</h1>
<main>
  <div class="sg-container mt-4 p-4">
    <form action="" class="sg-content" method="POST">
      {% csrf_token %} 
      
      {{ form|crispy }}
      <div class="col text-center mb-4 mt-5">
        <hr>
        <button type="submit" class="btn btn-warning btn-block">Adicionar</button>
      </div>
    </form>
    <hr>
    <a href="{% url 'crud_app:list' %}"><button class="btn btn-secondary btn-block mx-5">Voltar</button></a>
  </div>
</main>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'js/tabela.js' %}"></script>
{% endblock scripts %}

crud_app/templates/crud_app/detail.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block title %}<title>{{ conta.desc }}</title>{% endblock title %}
{% block content %}
<h1 class="d-flex justify-content-center mt-3">Detalhes</h1>
<main>
    <div class="jumbotron container">
        <h2>Conta:</h2>
        <hr>
        <p class="mb-5">{{conta.desc}}</p>
        <h2 class="mt-5">Fornecedor:</h2>
        <hr>
        <p>{{conta.fornecedor}}</p>
        <p>{{fornecedor.documento}}</p>
        <div class="text-center mt-5 pt-5">
            <a href="{% url 'crud_app:list' %}" class="mx-3" title="Ver Tabela"><button class="btn btn-secondary">Voltar</button></a>
            <a href="{% url 'crud_app:update' pk=conta.pk %}" class="mx-3" title="Editar Conta"><button class="btn btn-primary">Editar</button></a>
            <a href="{% url 'crud_app:delete' pk=conta.pk %}" class="mx-3" title="Excluir Conta"><button class="btn btn-danger">Excluir</button></a>
        </div>
    </div>
</main>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/tabela.js' %}"></script>
    <script src="{% static 'js/exportExcel.js' %}"></script>
{% endblock scripts %}

crud_app/templates/crud_app/excluir-cadastro.html
{% extends 'crud_app/base.html' %} 
{% load static %} 
{% load crispy_forms_tags%} 
{% block title %}
<title>Excluir</title>
{% endblock title %} 
{% block content %}
<h1 class="d-flex justify-content-center mt-3">
Excluir Conta
</h1>
<main>
  <div class="sg-container mt-4 p-4">
    <form action="" class="sg-content" method="POST">
      <div>
        <h3>Você tem certeza que quer excluir: {{ object.desc }}?</h3>
        <p>O fornecedor <strong>{{ object.fornecedor}}</strong> não será excluído, nem outras contas que ele tenha cadastrado</p>
      </div>
        
      {% csrf_token %} 
      
      {{ form|crispy }}
      <div class="col text-center mb-4 mt-5">
        <button type="submit" class="btn btn-danger btn-block">Excluir</button>
      </div>
    </form>
    <hr>
    <a href="{% url 'crud_app:list' %}"><button class="btn btn-secondary btn-block mx-5">Voltar</button></a>
  </div>
</main>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'js/tabela.js' %}"></script>
{% endblock scripts %}

crud_app/templates/crud_app/index.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block styles %}
	<link rel="stylesheet" href="{% static 'css/index.css' %}">    
{% endblock  %}

{% block content %}
	<div class="image-background mt-0"><img src="{% static 'img/Safegold-Background.jpg' %}"></div>
{% endblock %}
{% block scripts %}
<script src="{% static 'crud_app/js/index.js' %}"></script>

{% endblock scripts %}

crud_app/templates/crud_app/tabela.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% load crispy_forms_tags%} 
{% block title %}<title>Tabela</title>{% endblock title %}
{% block content %}
<main>
    <div class="container-fluid" style="margin-bottom:150px;">
        <div class="row">
            <div class="col sg-container mt-2 mx-3 ignore-on-print">
                <h3 class="text-center">Adicionar</h3>
                <form action="" class="sg-content" method="POST">
                    {% csrf_token %} 
                    
                    {{ form|crispy }}                
                    <!--======================================= APAGAR DEPOIS, SOMENTE PARA TESTES =======================================-->
                    <div class="input-group input-group-sm my-1 ml-3 mr-3">
                        <input type="text" name="id" class="form-control" aria-la bel="Large" placeholder="Adicionar ID" />
                    </div>
                    <div class="input-group input-group-sm my-1 ml-3 mr-3">
                        <input type="text" name="conta" class="form-control" aria-label="Large" placeholder="Adicionar conta" />
                    </div>
                    <div class="input-group input-group-sm my-1 ml-3 mr-3">
                        <input type="text" name="fornecedor" class="form-control" aria-label="Large" placeholder="Adicionar fornecedor" />
                    </div>
                    <!--======================================= APAGAR DEPOIS, SOMENTE PARA TESTES =======================================-->
                    <div class="col text-center mb-1 mt-1">
    
                        <hr>
                    
                        <button hx-post="#"hx-target="#list"type="submit" class="btn btn-warning btn-block">Adicionar</button>
                    </div>
                </form>
            </div>
            <div class="col sg-container mt-2 mx-3 ignore-on-print">
                <h3 class="text-center">Filtrar</h3>
                <form action="" class="sg-content" method="POST">
                    {% csrf_token %} 
                    
                    {{ form|crispy }}                
                    <!--======================================= APAGAR DEPOIS, SOMENTE PARA TESTES =======================================-->
                    <div class="input-group input-group-sm my-1 ml-3 mr-3">
                        <input type="text" name="id" class="form-control" aria-la bel="Large" placeholder="Filtrar por ID" />
                    </div>
                    <div class="input-group input-group-sm my-1 ml-3 mr-3">
                        <input type="text" name="conta" class="form-control" aria-label="Large" placeholder="Filtrar por conta" />
                    </div>
                    <div class="input-group input-group-sm my-1 ml-3 mr-3">
                        <input type="text" name="fornecedor" class="form-control" aria-label="Large" placeholder="Filtrar por fornecedor" />
                    </div>
                    <!--======================================= APAGAR DEPOIS, SOMENTE PARA TESTES =======================================-->
                    <div class="col text-center mb-1 mt-1">
    
                        <hr>
                        <button type="submit" class="btn btn-primary btn-block">Filtrar</button>
                    </div>
                </form>
            </div>
        </div>
        <div id='list'>
        <div class="sg-container mt-3 mx-1 mb-5" style="margin-bottom: 1px">
            <div class="sg-content">
                <h3 class="text-center mt-1">Tabela</h3>
                <table class="table table-Light table-bordered table-striped mb-3 mt-2">
                    <thead class="table-dark">
                        <tr>
                            <th class="col text-center">ID</th>
                            <th class="col">Conta</th>
                            <th class="col">Fornecedor</th>
                            <th class="col text-center sg-action-buttons excludeExport">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for conta in object_list %}
                        <tr>
                            <td class="text-center col-md-1">{{conta.id}}</td>
                            <td>{{conta.desc}}</td>
                            <td class="col-md-3">{{conta.fornecedor}}</td>
                            <td class="sg-action-buttons excludeExport text-center col-md-2">
                                <a href="{% url 'crud_app:detail' pk=conta.pk %}" class="mx-3" title="Detalhar Conta"><i class="fa-solid fa-expand"></i></a>   
                                <a href="{% url 'crud_app:update' pk=conta.pk %}" class="mx-3" title="Editar Conta"><i class="fa-solid fa-pen-to-square"></i></a>
                                <a href="{% url 'crud_app:delete' pk=conta.pk %}" class="mx-3" title="Excluir Conta"><i class="fa-solid fa-trash-can"></i></a>
                            </td>
                        </tr>
                        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        </div>
    </div>
</main>
<footer class="footer fixed-bottom">
    <div class="sg-footer-container">
        <p>Exportar dados:</p>
        <button type="button" class="btn btn-outline-dark sg-button" id="xlsxExport">Excel</button>
        <button type="button" class="btn btn-outline-dark sg-button" id="printExport">PDF</button>
    </div>
</footer>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/tabela.js' %}"></script>
    <script src="{% static 'js/exportExcel.js' %}"></script>
{% endblock scripts %}

crud_app/templates/crud_app/temp.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% load crispy_forms_tags%} 
{% block title %}<title>Tabela</title>{% endblock title %}
{% block content %}
<main>
    <div class="row">
        <div class="col sg-container mt-2">
            <p>Adicionar</p>
            <form action="" class="sg-content" method="POST">
                {% csrf_token %} 
                
                {{ form|crispy }}
                <div class="col text-center mb-1 mt-1">
                    <hr>
                    <button type="submit" class="btn btn-warning btn-block">Adicionar</button>
                </div>
            </form>
        </div>
        <div class="col">
            <div class="col sg-container mt-2">
                <p>Filtrar</p>
                <form action="" class="sg-content" method="POST">
                    {% csrf_token %} 
                    
                    {{ form|crispy }}
                    <div class="col text-center mb-1 mt-1">
                        <hr>
                        <button type="submit" class="btn btn-warning btn-block text-center">Adicionar</button>
                    </div>
                </form>
            </div>
        </div>  
    </div>

    <div class="sg-container mt-4">
        <div class="sg-content">
            <table class="table table-Light table-bordered table-striped mb-3 mt-3">
                <thead class="table-dark">
                    <tr>
                        <th class="col text-center">ID</th>
                        <th class="col">Conta</th>
                        <th class="col">Fornecedor</th>
                        <th class="col text-center sg-action-buttons excludeExport">Action</th>
                    </tr>
                </thead>
                <tbody hx-target = "closest tr" hx-swap="outerHTML">
                    {% for conta in object_list %}
                    <tr>
                        <td class="text-center col-md-1">{{conta.id}}</td>
                        <td>{{conta.desc}}</td>
                        <td class="col-md-3">{{conta.fornecedor}}</td>
                        <td>
                            <button class="btn btn-danger"
                                    hx-get="/crud_app/${conta.id}/edit"
                                    hx-trigger="edit"
                                    _="on click
                                        if .editing is not empty
                                            Swal.fire({title: 'Already Editing',
                                                        showCancelButton: true,
                                                        confirmButtonText: 'Yep, Edit This Row!',
                                                        text:'Hey!  You are already editing a row!  Do you want to cancel that edit and continue?'})
                                    if the result's isConfirmed is false
                                        halt
                                        end
                                        send cancel to .editing
                                    end
                                    trigger edit">
                             Edit
                            </button>
                        </td>
                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>
<footer class="footer fixed-bottom">
    <div class="sg-footer-container">
        <p>Exportar dados:</p>
        <button type="button" class="btn btn-outline-dark sg-button" id="xlsxExport">Excel</button>
        <button type="button" class="btn btn-outline-dark sg-button" id="printExport">PDF</button>
    </div>
</footer>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/tabela.js' %}"></script>
    <script src="{% static 'js/exportExcel.js' %}"></script>
{% endblock scripts %}

user/templates/index.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block styles %}
	<link rel="stylesheet" href="{% static 'css/index.css' %}">    
{% endblock  %}

{% block content %}
	<div class="image-background mt-0"><img src="{% static 'img/Safegold-Background.jpg' %}"></div>
{% endblock %}
{% block scripts %}
<script src="{% static 'crud_app/js/index.js' %}"></script>

{% endblock scripts %}